pipeline {
  agent {
    label 'agent1'
  }
  
  parameters {
    string name: 'IMAGE_NAME', defaultValue: 'query-server'
    string name: 'IMAGE_REGISTRY_ACCOUNT', defaultValue: 'hahajong'
  }

  stages {
    stage('Move directory and Copy test config file') {
      when {
        expression { 
            params.IMAGE_NAME == 'query-server' ||
            params.IMAGE_NAME == 'authentication'
        }
      }
      steps {
        sh "cp -rf query-server/* ."
        sh "mkdir -p ${env.WORKSPACE}/src/test/resources/"
        sh "cp /home/ubuntu/test-config/${params.IMAGE_NAME}/application-test.yml ${env.WORKSPACE}/src/test/resources/"
      }
    }

    stage('Test Gradle Project') {
      steps {
          sh './gradlew test --no-daemon'
      }
    }
    
    stage('Build Gradle Project') {
      steps {
          sh './gradlew build -x test --parallel --no-daemon'
      }
    }
    
    stage('Build Docker Image') {
      steps {
        sh "docker image build -t ${params.IMAGE_NAME} ."
      }
    }

    stage('Remove Docker Image') {
      when {
        not {
            anyOf {
            branch 'main';
            branch 'be-dev'
            }
        }
      }
      steps {
        sh "docker images ${params.IMAGE_NAME} -q | xargs docker rmi -f"
      }
    }


    stage('Tagging Docker Image') {
      when {
        anyOf {
          branch 'main';
          branch 'be-dev'
        }
      }
      steps {
        sh "docker image tag ${params.IMAGE_NAME} ${params.IMAGE_REGISTRY_ACCOUNT}/${params.IMAGE_NAME}:latest"
        sh "docker image tag ${params.IMAGE_NAME} ${params.IMAGE_REGISTRY_ACCOUNT}/${params.IMAGE_NAME}:${BUILD_NUMBER}"
      }
    }


    stage('Publish Docker Image') {
      when {
        anyOf {
          branch 'main';
          branch 'be-dev'
        }
      }
      steps {
        withDockerRegistry(credentialsId: 'docker-hub', url: 'https://index.docker.io/v1/') {
          sh "docker image push --all-tags ${params.IMAGE_REGISTRY_ACCOUNT}/${params.IMAGE_NAME}"
          sh "docker images ${params.IMAGE_NAME} -q | xargs docker rmi -f"
        }
      }
    }

    stage('Update Kubernetes manifests') {
      when {
        anyOf {
          branch 'main';
          branch 'be-dev'
        }
      }
      steps {
            git branch: 'main', credentialsId: 'cicd-sssdev', url: 'https://github.com/sss-develops/application-manifests.git'
            sh "./change-image-tag.sh ${params.IMAGE_REGISTRY_ACCOUNT} ${params.IMAGE_NAME} ${env.BUILD_NUMBER} ${env.WORKSPACE}"
            withCredentials([gitUsernamePassword(credentialsId: 'cicd-sssdev', gitToolName: 'Default')]) {
              sh "git push origin main"
            }
        }
    }
  }
}